# Copyright Â© 2018-2020 Hugo Locurcio and contributors - CC0 1.0 Universal
# See `LICENSE.md` included in the source distribution for details.

jobs:
  # Installs and uninstalls every package in the bucket
  # This is done to ensure URLs used in manifests are still functional
  - job: test
    condition: >-
      or(
        eq(variables['Build.Reason'], 'Schedule'),
        eq(variables['Build.Reason'], 'Manual')
      )
    pool:
      vmImage: vs2017-win2016
    steps:
      - powershell: |
          # Install Scoop
          iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
          scoop bucket add extras

          # Install packages
          Get-ChildItem "./bucket/*.json" | Foreach-Object {
              scoop install "./bucket/$($_.BaseName).json"
              scoop uninstall "$($_.BaseName)"
          }
