name: Tests

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test_powershell:
    name: WindowsPowerShell
    runs-on: windows-latest
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@main
        with:
          fetch-depth: 2
          path: "my_bucket"
      - name: Checkout Scoop
        uses: actions/checkout@main
        with:
          repository: ScoopInstaller/Scoop
          path: "scoop_core"
      - name: Install test modules (WindowsPowerShell)
        shell: powershell
        run: |
          try {
            Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted -ErrorAction SilentlyContinue
          } catch {}
          $modules = @(
            @{ Name = 'BuildHelpers'; Version = '2.0.1' },
            @{ Name = 'Pester';        Version = '5.2.0' }
          )
          foreach ($m in $modules) {
            $found = Get-Module -ListAvailable -Name $m.Name | Where-Object { $_.Version -ge [version]$m.Version }
            if (-not $found) {
              Install-Module -Name $m.Name -RequiredVersion $m.Version -Scope CurrentUser -Force -AllowClobber -Repository PSGallery
            }
          }
      - name: Init and Test
        shell: powershell
        run: |
          $env:SCOOP_HOME="$(Convert-Path '.\scoop_core')"
          .\scoop_core\test\bin\init.ps1
          .\my_bucket\bin\test.ps1
  test_pwsh:
    name: PowerShell
    runs-on: windows-latest
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@main
        with:
          fetch-depth: 2
          path: "my_bucket"
      - name: Checkout Scoop
        uses: actions/checkout@main
        with:
          repository: ScoopInstaller/Scoop
          path: "scoop_core"
      - name: Install test modules (pwsh)
        shell: pwsh
        run: |
          try {
            Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted -ErrorAction SilentlyContinue
          } catch {}
          $modules = @(
            @{ Name = 'BuildHelpers'; Version = '2.0.1' },
            @{ Name = 'Pester';        Version = '5.2.0' }
          )
          foreach ($m in $modules) {
            $found = Get-Module -ListAvailable -Name $m.Name | Where-Object { $_.Version -ge [version]$m.Version }
            if (-not $found) {
              Install-Module -Name $m.Name -RequiredVersion $m.Version -Scope CurrentUser -Force -AllowClobber -Repository PSGallery
            }
          }
      - name: Init and Test
        shell: pwsh
        run: |
          $env:SCOOP_HOME="$(Convert-Path '.\scoop_core')"
          .\scoop_core\test\bin\init.ps1
          .\my_bucket\bin\test.ps1
